// src/components/TopNavbar.tsx
import { Bell, ChevronDown, LogOut } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useRole } from "@/contexts/RoleContext";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

type SchoolSessionData = {
  adminInfo?: {
    name?: string;
    email?: string;
  };
  schoolInfo?: {
    logo?: string;
  };
};

type TeacherSessionData = {
  name?: string;
  email?: string;
};

const superAdminTitles: Record<string, string> = {
  "/": "Dashboard",
  "/schools": "Schools Management",
  "/school-admins": "School Admins",
  "/subscriptions": "Subscriptions",
  "/settings": "Settings",
  "/logs": "Activity Logs",
  "/security": "Security",
  "/user-change": "User Change",
};

function readJsonStorage<T>(key: string): T | null {
  const rawValue = localStorage.getItem(key);
  if (!rawValue) {
    return null;
  }

  try {
    return JSON.parse(rawValue) as T;
  } catch {
    return null;
  }
}

function getPageTitle(pathname: string, role: string) {
  if (role === "super-admin") {
    return superAdminTitles[pathname] || "Dashboard";
  }

  if (role === "school-admin" && pathname === "/school") {
    return "School Dashboard";
  }

  if (role === "teacher" && pathname === "/teacher") {
    return "Teacher Dashboard";
  }

  const segment = pathname.split("/").filter(Boolean).pop() || "dashboard";
  return segment.charAt(0).toUpperCase() + segment.slice(1).replace(/-/g, " ");
}

export function TopNavbar() {
  const location = useLocation();
  const navigate = useNavigate();
  const { role, logout } = useRole();

  const [schoolData, setSchoolData] = useState<SchoolSessionData | null>(null);
  const [teacherData, setTeacherData] = useState<TeacherSessionData | null>(null);

  useEffect(() => {
    const loadSessionData = () => {
      setSchoolData(readJsonStorage<SchoolSessionData>("school"));
      setTeacherData(readJsonStorage<TeacherSessionData>("teacher"));
    };

    loadSessionData();

    window.addEventListener("storage", loadSessionData);
    window.addEventListener("school-session-updated", loadSessionData);

    return () => {
      window.removeEventListener("storage", loadSessionData);
      window.removeEventListener("school-session-updated", loadSessionData);
    };
  }, []);

  const title = getPageTitle(location.pathname, role);

  const displayName =
    role === "school-admin"
      ? schoolData?.adminInfo?.name || "School Admin"
      : role === "teacher"
      ? teacherData?.name || "Teacher"
      : "Super Admin";

  const displayEmail =
    role === "school-admin"
      ? schoolData?.adminInfo?.email || "school-admin@mail.com"
      : role === "teacher"
      ? teacherData?.email || "teacher@mail.com"
      : "admin@eduadmin.com";

  const logo = schoolData?.schoolInfo?.logo;
  const hasValidLogo = Boolean(
    logo && (logo.startsWith("data:image") || logo.startsWith("http")),
  );

  const initials =
    displayName
      .split(" ")
      .filter(Boolean)
      .map((word) => word[0])
      .join("")
      .slice(0, 2)
      .toUpperCase() || "AD";

  const handleLogout = () => {
    const activeRole = role;
    logout();

    if (activeRole === "school-admin") {
      navigate("/school-admin-login", { replace: true });
      return;
    }

    navigate("/teacher-login", { replace: true });
  };

  return (
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-card px-6">
      <div>
        <h1 className="text-lg font-semibold text-foreground">{title}</h1>
        <p className="text-sm text-muted-foreground">Manage your workspace from one place.</p>
      </div>

      <div className="flex items-center gap-4">
        <button
          type="button"
          className="rounded-full border border-border p-2 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          aria-label="Notifications"
        >
          <Bell className="h-4 w-4" />
        </button>

        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <button
              type="button"
              className="flex items-center gap-3 rounded-full border border-border px-2 py-1.5 transition-colors hover:bg-muted"
            >
              {hasValidLogo ? (
                <img
                  src={logo}
                  alt={displayName}
                  className="h-9 w-9 rounded-full object-cover"
                />
              ) : (
                <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground">
                  {initials}
                </div>
              )}

              <div className="hidden text-left sm:block">
                <p className="text-sm font-medium text-foreground">{displayName}</p>
                <p className="text-xs text-muted-foreground">{displayEmail}</p>
              </div>

              <ChevronDown className="h-4 w-4 text-muted-foreground" />
            </button>
          </DropdownMenuTrigger>

          <DropdownMenuContent align="end" className="w-56">
            <div className="px-2 py-1.5">
              <p className="text-sm font-semibold">{displayName}</p>
              <p className="text-xs text-muted-foreground">{displayEmail}</p>
            </div>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              className="cursor-pointer text-red-600 focus:bg-red-50 focus:text-red-600"
              onClick={handleLogout}
            >
              <LogOut className="mr-2 h-4 w-4" />
              Logout
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
}

// frontend-svelte/src/lib/components/layout/TopNavbar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { Bell, ChevronDown, LogOut, PencilLine } from 'lucide-svelte';
  import type { User } from '$lib/types';
  import { schoolStore } from '$lib/stores/school';

  let { user }: { user: User | undefined } = $props();

  let dropdownOpen = $state(false);

  const role = $derived(user?.role ?? 'super-admin');
  const currentPath = $derived($page.url.pathname);

  const superAdminTitles: Record<string, string> = {
    '/dashboard': 'Dashboard',
    '/schools': 'Schools Management',
    '/school-admins': 'School Admins',
    '/subscriptions': 'Subscriptions',
    '/settings': 'Settings',
    '/logs': 'Activity Logs',
    '/security': 'Security',
    '/user-change': 'User Change',
  };

  const title = $derived((() => {
    if (role === 'super-admin') return superAdminTitles[currentPath] ?? 'Dashboard';
    if (role === 'school-admin' && currentPath === '/school') return 'School Dashboard';
    if (role === 'teacher' && currentPath === '/teacher') return 'Teacher Dashboard';
    const segment = currentPath.split('/').filter(Boolean).pop() ?? 'dashboard';
    return segment.charAt(0).toUpperCase() + segment.slice(1).replace(/-/g, ' ');
  })());

  const displayName = $derived(user?.name ?? (role === 'super-admin' ? 'Super Admin' : role === 'school-admin' ? 'School Admin' : 'Teacher'));
  const displayEmail = $derived(user?.email ?? '');

  const initials = $derived(
    displayName
      .split(' ')
      .filter(Boolean)
      .map((w: string) => w[0])
      .join('')
      .slice(0, 2)
      .toUpperCase() || 'AD'
  );

  // Admin photo: prefer fetched from store (includes base64), fall back to cookie URL
  const adminPhoto = $derived(
    $schoolStore.adminPhoto || user?.adminPhoto || ''
  );
  const showAdminPhoto = $derived(
    !!adminPhoto && (adminPhoto.startsWith('data:image') || adminPhoto.startsWith('http'))
  );

  function closeDropdown() {
    dropdownOpen = false;
  }
</script>

<svelte:window onclick={(e) => { if (!(e.target as Element).closest('.navbar-dropdown')) dropdownOpen = false; }} />

<header class="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-card px-6">
  <div>
    <h1 class="text-lg font-semibold text-foreground">{title}</h1>
    <p class="text-sm text-muted-foreground">Manage your workspace from one place.</p>
  </div>

  <div class="flex items-center gap-4">
    <button
      type="button"
      class="rounded-full border border-border p-2 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
      aria-label="Notifications"
    >
      <Bell class="h-4 w-4" />
    </button>

    <!-- User dropdown -->
    <div class="relative navbar-dropdown">
      <button
        type="button"
        onclick={() => (dropdownOpen = !dropdownOpen)}
        class="flex items-center gap-3 rounded-full border border-border bg-background/80 px-2 py-1.5 shadow-sm backdrop-blur transition-colors hover:bg-muted"
      >
        {#if showAdminPhoto}
          <img src={adminPhoto} alt={displayName} class="h-9 w-9 rounded-full object-cover shadow-sm" />
        {:else}
          <div class="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-xs font-semibold text-primary-foreground shadow-sm">
            {initials}
          </div>
        {/if}
        <div class="hidden text-left sm:block">
          <p class="text-sm font-medium text-foreground">{displayName}</p>
          <p class="text-xs text-muted-foreground">{displayEmail}</p>
        </div>
        <ChevronDown class="h-4 w-4 text-muted-foreground" />
      </button>

      {#if dropdownOpen}
        <div class="absolute right-0 top-full mt-2 w-56 rounded-xl border border-border bg-card shadow-lg z-50">
          <div class="px-3 py-2.5 border-b border-border">
            <p class="text-sm font-semibold">{displayName}</p>
            <p class="text-xs text-muted-foreground">{displayEmail}</p>
          </div>

          {#if role === 'school-admin'}
            <a
              href="/school/profile"
              onclick={closeDropdown}
              class="flex w-full items-center gap-2 px-3 py-2 text-sm hover:bg-muted transition-colors"
            >
              <PencilLine class="h-4 w-4" />
              View Profile
            </a>
            <div class="border-t border-border"></div>
          {/if}

          <form method="POST" action="/logout">
            <button
              type="submit"
              class="flex w-full items-center gap-2 px-3 py-2 text-sm text-red-600 hover:bg-red-50 transition-colors rounded-b-xl"
            >
              <LogOut class="h-4 w-4" />
              Logout
            </button>
          </form>
        </div>
      {/if}
    </div>
  </div>
</header>
